//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class ObjectMsg : Message
    {
        public const string k_RosMessageName = "customed_interfaces/Object";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public int id;
        public Geometry.PoseMsg pose;
        public Geometry.Vector3Msg scale;

        public ObjectMsg()
        {
            this.name = "";
            this.id = 0;
            this.pose = new Geometry.PoseMsg();
            this.scale = new Geometry.Vector3Msg();
        }

        public ObjectMsg(string name, int id, Geometry.PoseMsg pose, Geometry.Vector3Msg scale)
        {
            this.name = name;
            this.id = id;
            this.pose = pose;
            this.scale = scale;
        }

        public static ObjectMsg Deserialize(MessageDeserializer deserializer) => new ObjectMsg(deserializer);

        private ObjectMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.id);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.scale = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.id);
            serializer.Write(this.pose);
            serializer.Write(this.scale);
        }

        public override string ToString()
        {
            return "ObjectMsg: " +
            "\nname: " + name.ToString() +
            "\nid: " + id.ToString() +
            "\npose: " + pose.ToString() +
            "\nscale: " + scale.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
