//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class TempMsg : Message
    {
        public const string k_RosMessageName = "customed_interfaces/Temp";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public int number;

        public TempMsg()
        {
            this.name = "";
            this.number = 0;
        }

        public TempMsg(string name, int number)
        {
            this.name = name;
            this.number = number;
        }

        public static TempMsg Deserialize(MessageDeserializer deserializer) => new TempMsg(deserializer);

        private TempMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.number);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.number);
        }

        public override string ToString()
        {
            return "TempMsg: " +
            "\nname: " + name.ToString() +
            "\nnumber: " + number.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
