//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomInterfaces
{
    [Serializable]
    public class WallMsg : Message
    {
        public const string k_RosMessageName = "custom_interfaces/Wall";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public Geometry.Vector3Msg position;
        public Geometry.Vector3Msg rotation;
        public Geometry.Vector3Msg scale;

        public WallMsg()
        {
            this.id = 0;
            this.position = new Geometry.Vector3Msg();
            this.rotation = new Geometry.Vector3Msg();
            this.scale = new Geometry.Vector3Msg();
        }

        public WallMsg(int id, Geometry.Vector3Msg position, Geometry.Vector3Msg rotation, Geometry.Vector3Msg scale)
        {
            this.id = id;
            this.position = position;
            this.rotation = rotation;
            this.scale = scale;
        }

        public static WallMsg Deserialize(MessageDeserializer deserializer) => new WallMsg(deserializer);

        private WallMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.position = Geometry.Vector3Msg.Deserialize(deserializer);
            this.rotation = Geometry.Vector3Msg.Deserialize(deserializer);
            this.scale = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.position);
            serializer.Write(this.rotation);
            serializer.Write(this.scale);
        }

        public override string ToString()
        {
            return "WallMsg: " +
            "\nid: " + id.ToString() +
            "\nposition: " + position.ToString() +
            "\nrotation: " + rotation.ToString() +
            "\nscale: " + scale.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
