//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class EditObjectsRequest : Message
    {
        public const string k_RosMessageName = "customed_interfaces/EditObjects";
        public override string RosMessageName => k_RosMessageName;

        public string function;
        public ObjectMsg @object;

        public EditObjectsRequest()
        {
            this.function = "";
            this.@object = new ObjectMsg();
        }

        public EditObjectsRequest(string function, ObjectMsg @object)
        {
            this.function = function;
            this.@object = @object;
        }

        public static EditObjectsRequest Deserialize(MessageDeserializer deserializer) => new EditObjectsRequest(deserializer);

        private EditObjectsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.function);
            this.@object = ObjectMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.function);
            serializer.Write(this.@object);
        }

        public override string ToString()
        {
            return "EditObjectsRequest: " +
            "\nfunction: " + function.ToString() +
            "\n@object: " + @object.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
