//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class RequestCategoryRequest : Message
    {
        public const string k_RosMessageName = "customed_interfaces/RequestCategory";
        public override string RosMessageName => k_RosMessageName;

        public string category;

        public RequestCategoryRequest()
        {
            this.category = "";
        }

        public RequestCategoryRequest(string category)
        {
            this.category = category;
        }

        public static RequestCategoryRequest Deserialize(MessageDeserializer deserializer) => new RequestCategoryRequest(deserializer);

        private RequestCategoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.category);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.category);
        }

        public override string ToString()
        {
            return "RequestCategoryRequest: " +
            "\ncategory: " + category.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
