//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class RequestHistoryRequest : Message
    {
        public const string k_RosMessageName = "customed_interfaces/RequestHistory";
        public override string RosMessageName => k_RosMessageName;


        public RequestHistoryRequest()
        {
        }
        public static RequestHistoryRequest Deserialize(MessageDeserializer deserializer) => new RequestHistoryRequest(deserializer);

        private RequestHistoryRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "RequestHistoryRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
