//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class RequestSTODResponse : Message
    {
        public const string k_RosMessageName = "customed_interfaces/RequestSTOD";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public RequestSTODResponse()
        {
            this.success = false;
        }

        public RequestSTODResponse(bool success)
        {
            this.success = success;
        }

        public static RequestSTODResponse Deserialize(MessageDeserializer deserializer) => new RequestSTODResponse(deserializer);

        private RequestSTODResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "RequestSTODResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
