//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.CustomedInterfaces
{
    [Serializable]
    public class RequestSTODRequest : Message
    {
        public const string k_RosMessageName = "customed_interfaces/RequestSTOD";
        public override string RosMessageName => k_RosMessageName;

        public string agent_name;

        public RequestSTODRequest()
        {
            this.agent_name = "";
        }

        public RequestSTODRequest(string agent_name)
        {
            this.agent_name = agent_name;
        }

        public static RequestSTODRequest Deserialize(MessageDeserializer deserializer) => new RequestSTODRequest(deserializer);

        private RequestSTODRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.agent_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.agent_name);
        }

        public override string ToString()
        {
            return "RequestSTODRequest: " +
            "\nagent_name: " + agent_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
